### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by Iquaridys** [supreen/Php-Sql-admin-panel#1] opened 2022-07-22 02:46 UTC
I got error when run index.php , 

 Parse error: syntax error, unexpected end of file in C:\laragon\www\Php-Sql-admin-panel-master\index.php on line 171
 
 btw can i request something?
 can you add example like create,delete,modif/update database

**Comment by supreen** [comment] 2022-07-23 13:31
I am unable to reproduce the error. 
I had downloaded it and checked it again. Everything is working fine. 
Please check the following files:
1- database.php (make sure that every data entered there is accessible and correct. including SQL credentials and Captcha settings)
2- SQL.sql (please make sure that you had imported the SQL.sql in your sql database)
If you are unable to complete step 2. please manually add these things into your "PHPMYADMIN"
a- create a database and create a table under it which shall be named "control"
b- the "control" table must have following columns (i-user ii-pass iii-start iv-end)
c- add a value (you can leave the 'start' and 'end' blank).
  
It should work after that. 


However, On your request I had updated the code today 
1- The NAVBAR and INDEX in functional now. 
2- You can add your codes in the resources folder. 
3- The "setting" tabs allow you to "delete" , "edit" and "add" new users and passwords. (you can use same code to understand how databases are created, deleted, modified and updated using php)
4- if you are using updated version, you will need one more column in the control i.e "id". it is created to help you easily identify the data, which shall help you in creating, deleting and editing the value.

P.S this code uses complicated Javascripts and jquery to change the values in a blink of the eyes  and without a refresh. 
Do not touch any file which has "_" into it or it can break the code.

**Comment by supreen** [comment] 2022-07-24 14:34
The demo is added for your understanding. I am closing this threat now. Feel free to reach me.

**Closed as completed by supreen** 2022-07-24 14:34 UTC
